# Generated by Django 3.2.4 on 2021-07-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210730_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elog',
            name='length_of_time',
        ),
        migrations.AddField(
            model_name='elog',
            name='length_of_time_minutes',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elog',
            name='calories_burned',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='elog',
            name='distance_miles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='elog',
            name='intensity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='elog',
            name='pace_minutes_per_mile',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='elog',
            name='reps_laps',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='elog',
            name='weight_pounds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
