# Generated by Django 3.2.4 on 2021-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210730_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elog',
            name='distance_miles',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
