# Generated by Django 3.2.4 on 2021-07-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_elog_distance_miles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elog',
            name='distance_miles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
